---
title: 'SmartDogHouse'
author:
- Gyordan Caminati
- Sara Kiade
- Igor Lirussi
#keywords: [nothing, nothingness]
lang: it
toc-title: "" 
biblio-title: ""
abstract: |
  This is the abstract.

  It consists of two paragraphs.
...
